import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { HardwareDescription, GenerateOptions, GeneratedFile } from '../types';
import type { KnowledgeContext } from '../validator';

/**
 * Generate AI annotation reference — documents all @ai-* markers
 * in the generated project so agents and humans can understand
 * what each annotation means and how to respect it.
 */
export async function generateAnnotationRef(
  hw: HardwareDescription,
  options: GenerateOptions,
  kb: KnowledgeContext,
): Promise<GeneratedFile[]> {
  const activeJoints = hw.joints.filter((j) => j.type === 'active');

  let content = `# AI Annotation Reference — ${hw.robot.name}

> Auto-generated by Hermod. This document explains every \`@ai-*\` annotation
> in the generated codebase. AI agents MUST respect these boundaries.

## Annotation Quick Reference

| Annotation | Meaning | Agent Behavior |
|------------|---------|---------------|
| \`@ai-lock\` | Physical safety boundary — **ABSOLUTELY DO NOT MODIFY** | Read-only. Modification requires operator override. |
| \`@ai-critical\` | Important parameter — **requires human confirmation** | May suggest changes, but must request approval. |
| \`@ai-default\` | Experience-based default — **can change with justification** | May modify, must document reasoning. |
| \`@ai-context\` | Module description — **informational only** | No restriction. Helps agent understand the system. |
| \`@ai-extend\` | Extension point — **safe to add new code** | Agent may add code below this marker freely. |
| \`@ai-telemetry\` | Observable data channel — **readable at runtime** | Agent may read for debugging/tuning purposes. |

## @ai-lock Values — DO NOT MODIFY

`;

  for (const joint of activeJoints) {
    const motor = kb.motors.get(joint.motor);
    if (!motor) continue;
    content += `### ${joint.name} (${motor.id})

| Parameter | Value | Reason |
|-----------|-------|--------|
| Max current | ${motor.safety.maxCurrentA}A | Driver chip physical limit |
| Max temperature | ${motor.safety.maxTempC}°C | Magnet demagnetization threshold |
| Max speed | ${motor.safety.maxSpeedRpm} RPM | Mechanical limit |
`;
    if (motor.safety.watchdogTimeoutMs) {
      content += `| Watchdog timeout | ${motor.safety.watchdogTimeoutMs}ms | Motor comm loss detection |
`;
    }
    content += '\n';
  }

  content += `## @ai-critical Values — MODIFY WITH CAUTION

All PID gains in \`firmware/src/motor_foc.cpp\` are marked \`@ai-critical\`.
Modify only after:
1. Running a step-response test on real hardware
2. Verifying no oscillation/instability
3. Getting operator approval

## @ai-extend Locations

- \`firmware/inc/can_config.h\` — Add custom CAN message structs
- \`firmware/inc/safety/limits.h\` — Add project-specific safety limits
- \`firmware/src/motor_foc.cpp\` — Add custom control modes
- \`urdf/*.urdf.xacro\` — Add custom links, plugins, transmissions
- \`ros2_ws/src/hermod_hardware/src/hardware_interface.cpp\` — Add custom interfaces
- \`CLAUDE.md\` — Add project-specific AI agent instructions

---

*Generated by Hermod — see the Hermod documentation for the full annotation specification.*
`;

  const outputPath = 'docs/AI_ANNOTATIONS.md';
  await fs.mkdir(path.join(options.outputDir, 'docs'), { recursive: true });
  await fs.writeFile(path.join(options.outputDir, outputPath), content, 'utf-8');

  return [
    { path: outputPath, content },
  ];
}
