import { renderAndWrite } from '../renderer';
import type { HardwareDescription, GenerateOptions, GeneratedFile } from '../types';
import type { KnowledgeContext } from '../validator';

/**
 * Generate Gazebo simulation world and Docker Compose.
 */
export async function generateGazebo(
  hw: HardwareDescription,
  options: GenerateOptions,
  templatesDir: string,
  kb?: KnowledgeContext,
): Promise<GeneratedFile[]> {
  const robotName = hw.robot.name.replace(/\s+/g, '_').toLowerCase();
  const rosNs = hw.ros?.namespace ?? 'hermod_robot';

  const activeJoints = hw.joints
    .filter((j) => j.type === 'active')
    .map((j) => ({
      ...j,
      motorEntry: kb?.motors.get(j.motor) ?? null,
    }));

  const sensors = hw.sensors.map((s) => ({
    ...s,
    sensorEntry: kb?.sensors.get(s.model) ?? null,
  }));

  const context = {
    robot: hw.robot,
    robotName,
    rosNs,
    activeJoints,
    sensors,
  };

  // SDF world from EJS template
  await renderAndWrite(templatesDir, 'sim/gazebo/world.sdf.ejs', options.outputDir,
    `sim/gazebo/${robotName}.sdf`, context);

  // Docker Compose
  const composeYaml = `# Docker Compose — Auto-generated by Hermod
# Start simulation: docker compose up

services:
  gazebo:
    image: osrf/ros:${hw.ros?.version ?? 'humble'}-desktop-full
    container_name: ${robotName}_sim
    environment:
      - DISPLAY=\${DISPLAY:-\'\'}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./sim/gazebo:/workspace/sim/gazebo:ro
      - ./urdf:/workspace/urdf:ro
      - ./ros2_ws:/workspace/ros2_ws:ro
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
    command: >
      bash -c "source /opt/ros/${hw.ros?.version ?? 'humble'}/setup.bash &&
               source /workspace/ros2_ws/install/setup.bash 2>/dev/null || true &&
               gazebo --verbose /workspace/sim/gazebo/${robotName}.sdf"
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
`;

  const composePath = 'docker-compose.yml';
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  await fs.mkdir(path.join(options.outputDir, 'docker'), { recursive: true });
  await fs.writeFile(path.join(options.outputDir, composePath), composeYaml, 'utf-8');

  // Entrypoint script
  const entrypoint = `#!/bin/bash
# Hermod Simulation Entrypoint
set -e
source /opt/ros/${hw.ros?.version ?? 'humble'}/setup.bash
source /workspace/ros2_ws/install/setup.bash 2>/dev/null || true
exec "\$@"
`;
  await fs.writeFile(path.join(options.outputDir, 'docker/entrypoint.sh'), entrypoint, 'utf-8');
  await fs.chmod(path.join(options.outputDir, 'docker/entrypoint.sh'), 0o755);

  return [
    { path: `sim/gazebo/${robotName}.sdf`, content: '' },
    { path: composePath, content: composeYaml },
    { path: 'docker/entrypoint.sh', content: entrypoint },
  ];
}
