import path from 'node:path';
import { promises as fs } from 'node:fs';
import type { HardwareDescription, GenerateOptions, GeneratedFile } from '../types';

/**
 * Generate Gazebo simulation configuration.
 */
export async function generateGazebo(
  _hw: HardwareDescription,
  options: GenerateOptions,
  _templatesDir: string,
): Promise<GeneratedFile[]> {
  const robotName = _hw.robot.name.replace(/\s+/g, '_').toLowerCase();

  const sdfContent = `<?xml version="1.0"?>
<!-- Gazebo Simulation — Auto-generated by Hermod -->
<sdf version="1.9">
  <world name="${robotName}_world">
    <include>
      <uri>model://sun</uri>
    </include>
    <include>
      <uri>model://ground_plane</uri>
    </include>

    <model name="${robotName}">
      <pose>0 0 0.1 0 0 0</pose>
      <link name="base_link">
        <inertial>
          <mass>5.0</mass>
          <inertia>
            <ixx>0.1</ixx><ixy>0</ixy><ixz>0</ixz>
            <iyy>0.1</iyy><iyz>0</iyz>
            <izz>0.1</izz>
          </inertia>
        </inertial>
        <visual name="chassis">
          <geometry><box><size>0.3 0.2 0.15</size></box></geometry>
        </visual>
        <collision name="chassis_collision">
          <geometry><box><size>0.3 0.2 0.15</size></box></geometry>
        </collision>
      </link>
    </model>
  </world>
</sdf>`;

  const worldPath = `sim/gazebo/${robotName}.sdf`;
  await fs.mkdir(path.join(options.outputDir, 'sim/gazebo'), { recursive: true });
  await fs.writeFile(path.join(options.outputDir, worldPath), sdfContent, 'utf-8');

  // Docker compose
  const composeYaml = `# Docker Compose — Auto-generated by Hermod
# Start with: docker compose up
services:
  gazebo:
    image: ghcr.io/hermod-robotics/gazebo-ros2:latest
    container_name: ${robotName}_sim
    environment:
      - DISPLAY=\${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./sim/gazebo:/workspace/sim/gazebo:ro
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               gazebo --verbose /workspace/sim/gazebo/${robotName}.sdf"
    network_mode: host
`;

  const composePath = 'docker-compose.yml';
  await fs.writeFile(path.join(options.outputDir, composePath), composeYaml, 'utf-8');

  return [
    { path: worldPath, content: sdfContent },
    { path: composePath, content: composeYaml },
  ];
}
